#!/usr/bin/env node
/**
 * Import shows from the old Version Radio site(s):
 *   - WordPress events: https://version.nz/wp-json/wp/v2/event
 *   - ICS recurrence files: https://radio.version.nz/ics/*.ics
 *
 * Emits idempotent SQL (INSERT OR IGNORE) to stdout for:
 *   npx wrangler d1 execute version-radio-db --local  --file import.sql
 *   npx wrangler d1 execute version-radio-db --remote --file import.sql
 */
import fs from 'node:fs';

const WP_URL = 'https://version.nz/wp-json/wp/v2/event?per_page=100';
const NOW = Math.floor(Date.now() / 1000);

function pad(n) {
	return String(n).padStart(2, '0');
}
function toDateStr(d) {
	return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())}`;
}
function addDays(dateStr, days) {
	const [y, m, d] = dateStr.split('-').map(Number);
	const date = new Date(Date.UTC(y, m - 1, d));
	date.setUTCDate(date.getUTCDate() + days);
	return toDateStr(date);
}
function todayStr() {
	return toDateStr(new Date());
}
function weekdayOf(dateStr) {
	const [y, m, d] = dateStr.split('-').map(Number);
	return new Date(Date.UTC(y, m - 1, d)).getUTCDay();
}
const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

/** Parse `DTSTART;TZID=...:YYYYMMDDTHHMMSS` and RRULE INTERVAL / BYDAY from an ICS. */
function parseIcsRecurrence(icsText) {
	const dtstart = [...icsText.matchAll(/DTSTART(?:;[^:]*)?:(\d{8})T(\d{6})/g)];
	const interval = [...icsText.matchAll(/INTERVAL=(\d+)/g)];
	const byday = [...icsText.matchAll(/RRULE[^\n]*BYDAY=([A-Z]{2})/g)];
	const dtend = [...icsText.matchAll(/DTEND(?:;[^:]*)?:(\d{8})T(\d{6})/g)];

	// The real show VEVENT is the one with the RRULE + a plausible DTSTART (not 1970).
	const vevent = dtstart
		.map((m) => ({ start: m[1], time: m[2] }))
		.find((m) => parseInt(m.start.slice(0, 4), 10) > 2000);
	if (!vevent) return null;

	const hh = parseInt(vevent.time.slice(0, 2), 10);
	const mm = parseInt(vevent.time.slice(2, 4), 10);
	const endTime = dtend.length ? dtend[dtend.length - 1][2] : vevent.time;

	const date = `${vevent.start.slice(0, 4)}-${vevent.start.slice(4, 6)}-${vevent.start.slice(6, 8)}`;
	return {
		anchor: date,
		startMinutes: hh * 60 + mm,
		durationMinutes: endTime === vevent.time ? 120 : Math.max(60, startMinutesDelta(vevent.time, endTime)),
		intervalWeeks: Math.max(1, Number(interval[interval.length - 1]?.[1] ?? 1)),
		weekday: DAY_NAMES[weekdayOf(date)]
	};
}

function startMinutesDelta(a, b) {
	const h1 = parseInt(a.slice(0, 2), 10);
	const m1 = parseInt(a.slice(2, 4), 10);
	const h2 = parseInt(b.slice(0, 2), 10);
	const m2 = parseInt(b.slice(2, 4), 10);
	return (h2 * 60 + m2) - (h1 * 60 + m1);
}

const esc = (s) => String(s).replaceAll("'", "''");

async function fetchText(url) {
	const res = await fetch(url, { headers: { 'user-agent': 'version-radio-import/1.0' } });
	if (!res.ok) throw new Error(`GET ${url} -> ${res.status}`);
	return res.text();
}

async function main() {
	const events = JSON.parse(await fetchText(WP_URL));
	const icsCache = new Map();
	const icsText = async (url) => {
		if (!url) return null;
		if (!icsCache.has(url)) icsCache.set(url, await fetchText(url));
		return icsCache.get(url);
	};

	/** @type {{title:string, anchor:string, startMinutes:number, durationMinutes:number, intervalWeeks:number}[]} */
	const shows = new Map();

	for (const ev of events) {
		const title = ev.title?.rendered?.trim() || ev.slug;
		const acf = ev.acf ?? {};
		const start = String(acf.event_start ?? '');
		if (!start) continue;
		const date = start.slice(0, 10);
		const [hh, mm] = start.slice(11).split(':').map(Number);
		const startMinutes = hh * 60 + mm;

		let rule = null;
		if (acf.cal_link) {
			rule = parseIcsRecurrence(await icsText(acf.cal_link));
		}

		// The four Wednesday rotation shows recur every 4 weeks from their event
		// date (the slot ICS is "rotating shows/hosts").
		const isWednesdayShow = new Set([
			'detunedradio',
			'version-excursions-26-8-5',
			'reasonable-dubs',
			'beats-reality'
		]).has(ev.slug);

		shows.set(ev.slug, {
			title,
			anchor: rule?.anchor ?? date,
			startMinutes: rule?.startMinutes ?? startMinutes,
			durationMinutes: rule?.durationMinutes ?? 120,
			intervalWeeks: rule?.intervalWeeks ?? (isWednesdayShow ? 4 : 1)
		});
	}

	const lines = [
		'-- Generated by scripts/import-shows.mjs — Version Radio shows (old app)',
		`-- Source: ${WP_URL}`,
		''
	];

	for (const [slug, show] of shows) {
		const showId = `scrape-${slug}`;
		lines.push(`INSERT OR IGNORE INTO show (id, dj_id, title, description, day_of_week, start_minutes, duration_minutes, interval_weeks, anchor_date, active, created_at, updated_at) VALUES ('${showId}', 'dj-station', '${esc(show.title)}', 'Imported from version.nz (${esc(slug)})', ${weekdayOf(show.anchor)}, ${show.startMinutes}, ${show.durationMinutes}, ${show.intervalWeeks}, '${show.anchor}', 1, ${NOW}, ${NOW});`);

		// Materialise broadcasts for the next 12 weeks.
		const horizon = addDays(todayStr(), 12 * 7);
		const intervalDays = show.intervalWeeks * 7;
		let k = 0;
		let date = show.anchor;
		while (date <= horizon) {
			const bid = `scrape-${slug}-${date}`;
			lines.push(`INSERT OR IGNORE INTO broadcast (id, show_id, date, start_minutes, duration_minutes, interval_weeks, created_at, updated_at) VALUES ('${bid}', '${showId}', '${date}', ${show.startMinutes}, ${show.durationMinutes}, ${show.intervalWeeks}, ${NOW}, ${NOW});`);
			k += 1;
			date = addDays(show.anchor, k * intervalDays);
		}
		lines.push('');
	}

	console.log(lines.join('\n'));
}

main().catch((err) => {
	console.error(err);
	process.exit(1);
});
